/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SalarieService } from "../salarie.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SalarieCreateInput } from "./SalarieCreateInput";
import { Salarie } from "./Salarie";
import { SalarieFindManyArgs } from "./SalarieFindManyArgs";
import { SalarieWhereUniqueInput } from "./SalarieWhereUniqueInput";
import { SalarieUpdateInput } from "./SalarieUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SalarieControllerBase {
  constructor(
    protected readonly service: SalarieService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Salarie })
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSalarie(
    @common.Body() data: SalarieCreateInput
  ): Promise<Salarie> {
    return await this.service.createSalarie({
      data: {
        ...data,

        affectations: {
          connect: data.affectations,
        },

        demenegament: {
          connect: data.demenegament,
        },

        domiciliation: {
          connect: data.domiciliation,
        },

        identite: {
          connect: data.identite,
        },

        telecom: data.telecom
          ? {
              connect: data.telecom,
            }
          : undefined,
      },
      select: {
        affectations: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        demenegament: {
          select: {
            id: true,
          },
        },

        domiciliation: {
          select: {
            id: true,
          },
        },

        id: true,

        identite: {
          select: {
            id: true,
          },
        },

        statutAdmr: true,
        statutVip: true,

        telecom: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Salarie] })
  @ApiNestedQuery(SalarieFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salaries(@common.Req() request: Request): Promise<Salarie[]> {
    const args = plainToClass(SalarieFindManyArgs, request.query);
    return this.service.salaries({
      ...args,
      select: {
        affectations: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        demenegament: {
          select: {
            id: true,
          },
        },

        domiciliation: {
          select: {
            id: true,
          },
        },

        id: true,

        identite: {
          select: {
            id: true,
          },
        },

        statutAdmr: true,
        statutVip: true,

        telecom: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Salarie })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salarie(
    @common.Param() params: SalarieWhereUniqueInput
  ): Promise<Salarie | null> {
    const result = await this.service.salarie({
      where: params,
      select: {
        affectations: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        demenegament: {
          select: {
            id: true,
          },
        },

        domiciliation: {
          select: {
            id: true,
          },
        },

        id: true,

        identite: {
          select: {
            id: true,
          },
        },

        statutAdmr: true,
        statutVip: true,

        telecom: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Salarie })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSalarie(
    @common.Param() params: SalarieWhereUniqueInput,
    @common.Body() data: SalarieUpdateInput
  ): Promise<Salarie | null> {
    try {
      return await this.service.updateSalarie({
        where: params,
        data: {
          ...data,

          affectations: {
            connect: data.affectations,
          },

          demenegament: {
            connect: data.demenegament,
          },

          domiciliation: {
            connect: data.domiciliation,
          },

          identite: {
            connect: data.identite,
          },

          telecom: data.telecom
            ? {
                connect: data.telecom,
              }
            : undefined,
        },
        select: {
          affectations: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          demenegament: {
            select: {
              id: true,
            },
          },

          domiciliation: {
            select: {
              id: true,
            },
          },

          id: true,

          identite: {
            select: {
              id: true,
            },
          },

          statutAdmr: true,
          statutVip: true,

          telecom: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Salarie })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSalarie(
    @common.Param() params: SalarieWhereUniqueInput
  ): Promise<Salarie | null> {
    try {
      return await this.service.deleteSalarie({
        where: params,
        select: {
          affectations: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          demenegament: {
            select: {
              id: true,
            },
          },

          domiciliation: {
            select: {
              id: true,
            },
          },

          id: true,

          identite: {
            select: {
              id: true,
            },
          },

          statutAdmr: true,
          statutVip: true,

          telecom: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
