/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Salarie as PrismaSalarie,
  Affectation as PrismaAffectation,
  Adresse as PrismaAdresse,
  Identite as PrismaIdentite,
  Telecom as PrismaTelecom,
} from "@prisma/client";

export class SalarieServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SalarieCountArgs, "select">): Promise<number> {
    return this.prisma.salarie.count(args);
  }

  async salaries(args: Prisma.SalarieFindManyArgs): Promise<PrismaSalarie[]> {
    return this.prisma.salarie.findMany(args);
  }
  async salarie(
    args: Prisma.SalarieFindUniqueArgs
  ): Promise<PrismaSalarie | null> {
    return this.prisma.salarie.findUnique(args);
  }
  async createSalarie(args: Prisma.SalarieCreateArgs): Promise<PrismaSalarie> {
    return this.prisma.salarie.create(args);
  }
  async updateSalarie(args: Prisma.SalarieUpdateArgs): Promise<PrismaSalarie> {
    return this.prisma.salarie.update(args);
  }
  async deleteSalarie(args: Prisma.SalarieDeleteArgs): Promise<PrismaSalarie> {
    return this.prisma.salarie.delete(args);
  }

  async getAffectations(parentId: string): Promise<PrismaAffectation | null> {
    return this.prisma.salarie
      .findUnique({
        where: { id: parentId },
      })
      .affectations();
  }

  async getDemenegament(parentId: string): Promise<PrismaAdresse | null> {
    return this.prisma.salarie
      .findUnique({
        where: { id: parentId },
      })
      .demenegament();
  }

  async getDomiciliation(parentId: string): Promise<PrismaAdresse | null> {
    return this.prisma.salarie
      .findUnique({
        where: { id: parentId },
      })
      .domiciliation();
  }

  async getIdentite(parentId: string): Promise<PrismaIdentite | null> {
    return this.prisma.salarie
      .findUnique({
        where: { id: parentId },
      })
      .identite();
  }

  async getTelecom(parentId: string): Promise<PrismaTelecom | null> {
    return this.prisma.salarie
      .findUnique({
        where: { id: parentId },
      })
      .telecom();
  }
}
