/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AffectationWhereUniqueInput } from "../../affectation/base/AffectationWhereUniqueInput";
import { ValidateNested, IsBoolean, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AdresseWhereUniqueInput } from "../../adresse/base/AdresseWhereUniqueInput";
import { IdentiteWhereUniqueInput } from "../../identite/base/IdentiteWhereUniqueInput";
import { TelecomWhereUniqueInput } from "../../telecom/base/TelecomWhereUniqueInput";

@InputType()
class SalarieCreateInput {
  @ApiProperty({
    required: true,
    type: () => AffectationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AffectationWhereUniqueInput)
  @Field(() => AffectationWhereUniqueInput)
  affectations!: AffectationWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @Field(() => AdresseWhereUniqueInput)
  demenegament!: AdresseWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @Field(() => AdresseWhereUniqueInput)
  domiciliation!: AdresseWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => IdentiteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => IdentiteWhereUniqueInput)
  @Field(() => IdentiteWhereUniqueInput)
  identite!: IdentiteWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  statutAdmr!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  statutVip!: boolean;

  @ApiProperty({
    required: false,
    type: () => TelecomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TelecomWhereUniqueInput)
  @IsOptional()
  @Field(() => TelecomWhereUniqueInput, {
    nullable: true,
  })
  telecom?: TelecomWhereUniqueInput | null;
}

export { SalarieCreateInput as SalarieCreateInput };
