/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AffectationWhereUniqueInput } from "../../affectation/base/AffectationWhereUniqueInput";
import { ValidateNested, IsOptional, IsBoolean } from "class-validator";
import { Type } from "class-transformer";
import { AdresseWhereUniqueInput } from "../../adresse/base/AdresseWhereUniqueInput";
import { IdentiteWhereUniqueInput } from "../../identite/base/IdentiteWhereUniqueInput";
import { TelecomWhereUniqueInput } from "../../telecom/base/TelecomWhereUniqueInput";

@InputType()
class SalarieUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AffectationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AffectationWhereUniqueInput)
  @IsOptional()
  @Field(() => AffectationWhereUniqueInput, {
    nullable: true,
  })
  affectations?: AffectationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @IsOptional()
  @Field(() => AdresseWhereUniqueInput, {
    nullable: true,
  })
  demenegament?: AdresseWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AdresseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdresseWhereUniqueInput)
  @IsOptional()
  @Field(() => AdresseWhereUniqueInput, {
    nullable: true,
  })
  domiciliation?: AdresseWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => IdentiteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => IdentiteWhereUniqueInput)
  @IsOptional()
  @Field(() => IdentiteWhereUniqueInput, {
    nullable: true,
  })
  identite?: IdentiteWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  statutAdmr?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  statutVip?: boolean;

  @ApiProperty({
    required: false,
    type: () => TelecomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TelecomWhereUniqueInput)
  @IsOptional()
  @Field(() => TelecomWhereUniqueInput, {
    nullable: true,
  })
  telecom?: TelecomWhereUniqueInput | null;
}

export { SalarieUpdateInput as SalarieUpdateInput };
