/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AffectationWhereUniqueInput } from "../../affectation/base/AffectationWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { AffectationListRelationFilter } from "../../affectation/base/AffectationListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PerimetreWhereUniqueInput } from "../../perimetre/base/PerimetreWhereUniqueInput";
import { EnumStructureTypeField } from "./EnumStructureTypeField";

@InputType()
class StructureWhereInput {
  @ApiProperty({
    required: false,
    type: () => AffectationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AffectationWhereUniqueInput)
  @IsOptional()
  @Field(() => AffectationWhereUniqueInput, {
    nullable: true,
  })
  affectationDomaine?: AffectationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AffectationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AffectationListRelationFilter)
  @IsOptional()
  @Field(() => AffectationListRelationFilter, {
    nullable: true,
  })
  affectations?: AffectationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  libell?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PerimetreWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PerimetreWhereUniqueInput)
  @IsOptional()
  @Field(() => PerimetreWhereUniqueInput, {
    nullable: true,
  })
  perimetre?: PerimetreWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumStructureTypeField,
  })
  @IsEnum(EnumStructureTypeField)
  @IsOptional()
  @Field(() => EnumStructureTypeField, {
    nullable: true,
  })
  typeField?: "Agence" | "Association" | "Federation";
}

export { StructureWhereInput as StructureWhereInput };
