/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StructureService } from "../structure.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StructureCreateInput } from "./StructureCreateInput";
import { Structure } from "./Structure";
import { StructureFindManyArgs } from "./StructureFindManyArgs";
import { StructureWhereUniqueInput } from "./StructureWhereUniqueInput";
import { StructureUpdateInput } from "./StructureUpdateInput";
import { AffectationFindManyArgs } from "../../affectation/base/AffectationFindManyArgs";
import { Affectation } from "../../affectation/base/Affectation";
import { AffectationWhereUniqueInput } from "../../affectation/base/AffectationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StructureControllerBase {
  constructor(
    protected readonly service: StructureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Structure })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStructure(
    @common.Body() data: StructureCreateInput
  ): Promise<Structure> {
    return await this.service.createStructure({
      data: {
        ...data,

        affectationDomaine: data.affectationDomaine
          ? {
              connect: data.affectationDomaine,
            }
          : undefined,

        perimetre: {
          connect: data.perimetre,
        },
      },
      select: {
        affectationDomaine: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        libell: true,

        perimetre: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Structure] })
  @ApiNestedQuery(StructureFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async structures(@common.Req() request: Request): Promise<Structure[]> {
    const args = plainToClass(StructureFindManyArgs, request.query);
    return this.service.structures({
      ...args,
      select: {
        affectationDomaine: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        libell: true,

        perimetre: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Structure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async structure(
    @common.Param() params: StructureWhereUniqueInput
  ): Promise<Structure | null> {
    const result = await this.service.structure({
      where: params,
      select: {
        affectationDomaine: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        libell: true,

        perimetre: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Structure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStructure(
    @common.Param() params: StructureWhereUniqueInput,
    @common.Body() data: StructureUpdateInput
  ): Promise<Structure | null> {
    try {
      return await this.service.updateStructure({
        where: params,
        data: {
          ...data,

          affectationDomaine: data.affectationDomaine
            ? {
                connect: data.affectationDomaine,
              }
            : undefined,

          perimetre: {
            connect: data.perimetre,
          },
        },
        select: {
          affectationDomaine: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          libell: true,

          perimetre: {
            select: {
              id: true,
            },
          },

          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Structure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStructure(
    @common.Param() params: StructureWhereUniqueInput
  ): Promise<Structure | null> {
    try {
      return await this.service.deleteStructure({
        where: params,
        select: {
          affectationDomaine: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          libell: true,

          perimetre: {
            select: {
              id: true,
            },
          },

          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/affectations")
  @ApiNestedQuery(AffectationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "read",
    possession: "any",
  })
  async findAffectations(
    @common.Req() request: Request,
    @common.Param() params: StructureWhereUniqueInput
  ): Promise<Affectation[]> {
    const query = plainToClass(AffectationFindManyArgs, request.query);
    const results = await this.service.findAffectations(params.id, {
      ...query,
      select: {
        activite: true,
        createdAt: true,

        domaine: {
          select: {
            id: true,
          },
        },

        id: true,

        salarie: {
          select: {
            id: true,
          },
        },

        structure: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/affectations")
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "update",
    possession: "any",
  })
  async connectAffectations(
    @common.Param() params: StructureWhereUniqueInput,
    @common.Body() body: AffectationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      affectations: {
        connect: body,
      },
    };
    await this.service.updateStructure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/affectations")
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "update",
    possession: "any",
  })
  async updateAffectations(
    @common.Param() params: StructureWhereUniqueInput,
    @common.Body() body: AffectationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      affectations: {
        set: body,
      },
    };
    await this.service.updateStructure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/affectations")
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "update",
    possession: "any",
  })
  async disconnectAffectations(
    @common.Param() params: StructureWhereUniqueInput,
    @common.Body() body: AffectationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      affectations: {
        disconnect: body,
      },
    };
    await this.service.updateStructure({
      where: params,
      data,
      select: { id: true },
    });
  }
}
