/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Habilitation } from "./Habilitation";
import { HabilitationCountArgs } from "./HabilitationCountArgs";
import { HabilitationFindManyArgs } from "./HabilitationFindManyArgs";
import { HabilitationFindUniqueArgs } from "./HabilitationFindUniqueArgs";
import { CreateHabilitationArgs } from "./CreateHabilitationArgs";
import { UpdateHabilitationArgs } from "./UpdateHabilitationArgs";
import { DeleteHabilitationArgs } from "./DeleteHabilitationArgs";
import { Perimetre } from "../../perimetre/base/Perimetre";
import { Utilisateur } from "../../utilisateur/base/Utilisateur";
import { HabilitationService } from "../habilitation.service";
@graphql.Resolver(() => Habilitation)
export class HabilitationResolverBase {
  constructor(protected readonly service: HabilitationService) {}

  async _habilitationsMeta(
    @graphql.Args() args: HabilitationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Habilitation])
  async habilitations(
    @graphql.Args() args: HabilitationFindManyArgs
  ): Promise<Habilitation[]> {
    return this.service.habilitations(args);
  }

  @graphql.Query(() => Habilitation, { nullable: true })
  async habilitation(
    @graphql.Args() args: HabilitationFindUniqueArgs
  ): Promise<Habilitation | null> {
    const result = await this.service.habilitation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Habilitation)
  async createHabilitation(
    @graphql.Args() args: CreateHabilitationArgs
  ): Promise<Habilitation> {
    return await this.service.createHabilitation({
      ...args,
      data: {
        ...args.data,

        perimetre: {
          connect: args.data.perimetre,
        },

        utilisateur: {
          connect: args.data.utilisateur,
        },
      },
    });
  }

  @graphql.Mutation(() => Habilitation)
  async updateHabilitation(
    @graphql.Args() args: UpdateHabilitationArgs
  ): Promise<Habilitation | null> {
    try {
      return await this.service.updateHabilitation({
        ...args,
        data: {
          ...args.data,

          perimetre: {
            connect: args.data.perimetre,
          },

          utilisateur: {
            connect: args.data.utilisateur,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Habilitation)
  async deleteHabilitation(
    @graphql.Args() args: DeleteHabilitationArgs
  ): Promise<Habilitation | null> {
    try {
      return await this.service.deleteHabilitation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Perimetre, {
    nullable: true,
    name: "perimetre",
  })
  async getPerimetre(
    @graphql.Parent() parent: Habilitation
  ): Promise<Perimetre | null> {
    const result = await this.service.getPerimetre(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Utilisateur, {
    nullable: true,
    name: "utilisateur",
  })
  async getUtilisateur(
    @graphql.Parent() parent: Habilitation
  ): Promise<Utilisateur | null> {
    const result = await this.service.getUtilisateur(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
