/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumIdentiteCivilite } from "./EnumIdentiteCivilite";
import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumIdentiteNationalite } from "./EnumIdentiteNationalite";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { Salarie } from "../../salarie/base/Salarie";
import { EnumIdentiteSexe } from "./EnumIdentiteSexe";

@ObjectType()
class Identite {
  @ApiProperty({
    required: false,
    enum: EnumIdentiteCivilite,
  })
  @IsEnum(EnumIdentiteCivilite)
  @IsOptional()
  @Field(() => EnumIdentiteCivilite, {
    nullable: true,
  })
  civilite?: "Homme" | "Femme" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  codeLieuNaissance!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  communeDeNaissance!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  dateNaissance!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  departementDeNaissance!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    enum: EnumIdentiteNationalite,
  })
  @IsEnum(EnumIdentiteNationalite)
  @Field(() => EnumIdentiteNationalite, {
    nullable: true,
  })
  nationalite?: "France" | "Autre";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  nomNaissance!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  nomUsuel!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numeroInsee!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  paysDeNaissance!: JsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  premierPrenom!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  prenoms!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  prenomUsuel!: string;

  @ApiProperty({
    required: true,
    type: () => Salarie,
  })
  @ValidateNested()
  @Type(() => Salarie)
  salarie?: Salarie | null;

  @ApiProperty({
    required: false,
    enum: EnumIdentiteSexe,
  })
  @IsEnum(EnumIdentiteSexe)
  @IsOptional()
  @Field(() => EnumIdentiteSexe, {
    nullable: true,
  })
  sexe?: "Feminin" | "Masculin" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Identite as Identite };
