/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Perimetre } from "./Perimetre";
import { PerimetreCountArgs } from "./PerimetreCountArgs";
import { PerimetreFindManyArgs } from "./PerimetreFindManyArgs";
import { PerimetreFindUniqueArgs } from "./PerimetreFindUniqueArgs";
import { CreatePerimetreArgs } from "./CreatePerimetreArgs";
import { UpdatePerimetreArgs } from "./UpdatePerimetreArgs";
import { DeletePerimetreArgs } from "./DeletePerimetreArgs";
import { HabilitationFindManyArgs } from "../../habilitation/base/HabilitationFindManyArgs";
import { Habilitation } from "../../habilitation/base/Habilitation";
import { Structure } from "../../structure/base/Structure";
import { PerimetreService } from "../perimetre.service";
@graphql.Resolver(() => Perimetre)
export class PerimetreResolverBase {
  constructor(protected readonly service: PerimetreService) {}

  async _perimetresMeta(
    @graphql.Args() args: PerimetreCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Perimetre])
  async perimetres(
    @graphql.Args() args: PerimetreFindManyArgs
  ): Promise<Perimetre[]> {
    return this.service.perimetres(args);
  }

  @graphql.Query(() => Perimetre, { nullable: true })
  async perimetre(
    @graphql.Args() args: PerimetreFindUniqueArgs
  ): Promise<Perimetre | null> {
    const result = await this.service.perimetre(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Perimetre)
  async createPerimetre(
    @graphql.Args() args: CreatePerimetreArgs
  ): Promise<Perimetre> {
    return await this.service.createPerimetre({
      ...args,
      data: {
        ...args.data,

        structure: {
          connect: args.data.structure,
        },
      },
    });
  }

  @graphql.Mutation(() => Perimetre)
  async updatePerimetre(
    @graphql.Args() args: UpdatePerimetreArgs
  ): Promise<Perimetre | null> {
    try {
      return await this.service.updatePerimetre({
        ...args,
        data: {
          ...args.data,

          structure: {
            connect: args.data.structure,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Perimetre)
  async deletePerimetre(
    @graphql.Args() args: DeletePerimetreArgs
  ): Promise<Perimetre | null> {
    try {
      return await this.service.deletePerimetre(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Habilitation], { name: "habilitations" })
  async findHabilitations(
    @graphql.Parent() parent: Perimetre,
    @graphql.Args() args: HabilitationFindManyArgs
  ): Promise<Habilitation[]> {
    const results = await this.service.findHabilitations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Structure, {
    nullable: true,
    name: "structure",
  })
  async getStructure(
    @graphql.Parent() parent: Perimetre
  ): Promise<Structure | null> {
    const result = await this.service.getStructure(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
