/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Telecom } from "./Telecom";
import { TelecomCountArgs } from "./TelecomCountArgs";
import { TelecomFindManyArgs } from "./TelecomFindManyArgs";
import { TelecomFindUniqueArgs } from "./TelecomFindUniqueArgs";
import { CreateTelecomArgs } from "./CreateTelecomArgs";
import { UpdateTelecomArgs } from "./UpdateTelecomArgs";
import { DeleteTelecomArgs } from "./DeleteTelecomArgs";
import { SalarieFindManyArgs } from "../../salarie/base/SalarieFindManyArgs";
import { Salarie } from "../../salarie/base/Salarie";
import { TelecomService } from "../telecom.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Telecom)
export class TelecomResolverBase {
  constructor(
    protected readonly service: TelecomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "read",
    possession: "any",
  })
  async _telecomsMeta(
    @graphql.Args() args: TelecomCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Telecom])
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "read",
    possession: "any",
  })
  async telecoms(
    @graphql.Args() args: TelecomFindManyArgs
  ): Promise<Telecom[]> {
    return this.service.telecoms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Telecom, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "read",
    possession: "own",
  })
  async telecom(
    @graphql.Args() args: TelecomFindUniqueArgs
  ): Promise<Telecom | null> {
    const result = await this.service.telecom(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Telecom)
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "create",
    possession: "any",
  })
  async createTelecom(
    @graphql.Args() args: CreateTelecomArgs
  ): Promise<Telecom> {
    return await this.service.createTelecom({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Telecom)
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "update",
    possession: "any",
  })
  async updateTelecom(
    @graphql.Args() args: UpdateTelecomArgs
  ): Promise<Telecom | null> {
    try {
      return await this.service.updateTelecom({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Telecom)
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "delete",
    possession: "any",
  })
  async deleteTelecom(
    @graphql.Args() args: DeleteTelecomArgs
  ): Promise<Telecom | null> {
    try {
      return await this.service.deleteTelecom(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Salarie], { name: "salarie" })
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "read",
    possession: "any",
  })
  async findSalarie(
    @graphql.Parent() parent: Telecom,
    @graphql.Args() args: SalarieFindManyArgs
  ): Promise<Salarie[]> {
    const results = await this.service.findSalarie(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
