/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TelecomService } from "../telecom.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TelecomCreateInput } from "./TelecomCreateInput";
import { Salarie } from "../../salarie/base/Salarie";
import { Telecom } from "./Telecom";
import { TelecomFindManyArgs } from "./TelecomFindManyArgs";
import { TelecomWhereUniqueInput } from "./TelecomWhereUniqueInput";
import { TelecomUpdateInput } from "./TelecomUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TelecomControllerBase {
  constructor(
    protected readonly service: TelecomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Telecom })
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTelecom(
    @common.Body() data: TelecomCreateInput
  ): Promise<Telecom> {
    return await this.service.createTelecom({
      data: {
        ...data,

        Salarie: {
          connect: data.Salarie,
        },
      },
      select: {
        createdAt: true,
        id: true,

        Salarie: {
          select: {
            id: true,
          },
        },

        typeMoyen: true,
        updatedAt: true,
        valeurMoyen: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Telecom] })
  @ApiNestedQuery(TelecomFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async telecoms(@common.Req() request: Request): Promise<Telecom[]> {
    const args = plainToClass(TelecomFindManyArgs, request.query);
    return this.service.telecoms({
      ...args,
      select: {
        createdAt: true,
        id: true,

        Salarie: {
          select: {
            id: true,
          },
        },

        typeMoyen: true,
        updatedAt: true,
        valeurMoyen: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Telecom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async telecom(
    @common.Param() params: TelecomWhereUniqueInput
  ): Promise<Telecom | null> {
    const result = await this.service.telecom({
      where: params,
      select: {
        createdAt: true,
        id: true,

        Salarie: {
          select: {
            id: true,
          },
        },

        typeMoyen: true,
        updatedAt: true,
        valeurMoyen: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Telecom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTelecom(
    @common.Param() params: TelecomWhereUniqueInput,
    @common.Body() data: TelecomUpdateInput
  ): Promise<Telecom | null> {
    try {
      return await this.service.updateTelecom({
        where: params,
        data: {
          ...data,

          Salarie: {
            connect: data.Salarie,
          },
        },
        select: {
          createdAt: true,
          id: true,

          Salarie: {
            select: {
              id: true,
            },
          },

          typeMoyen: true,
          updatedAt: true,
          valeurMoyen: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Telecom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Telecom",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTelecom(
    @common.Param() params: TelecomWhereUniqueInput
  ): Promise<Telecom | null> {
    try {
      return await this.service.deleteTelecom({
        where: params,
        select: {
          createdAt: true,
          id: true,

          Salarie: {
            select: {
              id: true,
            },
          },

          typeMoyen: true,
          updatedAt: true,
          valeurMoyen: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
