/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Affectation } from "./Affectation";
import { AffectationCountArgs } from "./AffectationCountArgs";
import { AffectationFindManyArgs } from "./AffectationFindManyArgs";
import { AffectationFindUniqueArgs } from "./AffectationFindUniqueArgs";
import { CreateAffectationArgs } from "./CreateAffectationArgs";
import { UpdateAffectationArgs } from "./UpdateAffectationArgs";
import { DeleteAffectationArgs } from "./DeleteAffectationArgs";
import { Structure } from "../../structure/base/Structure";
import { Salarie } from "../../salarie/base/Salarie";
import { AffectationService } from "../affectation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Affectation)
export class AffectationResolverBase {
  constructor(
    protected readonly service: AffectationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "read",
    possession: "any",
  })
  async _affectationsMeta(
    @graphql.Args() args: AffectationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Affectation])
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "read",
    possession: "any",
  })
  async affectations(
    @graphql.Args() args: AffectationFindManyArgs
  ): Promise<Affectation[]> {
    return this.service.affectations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Affectation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "read",
    possession: "own",
  })
  async affectation(
    @graphql.Args() args: AffectationFindUniqueArgs
  ): Promise<Affectation | null> {
    const result = await this.service.affectation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Affectation)
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "create",
    possession: "any",
  })
  async createAffectation(
    @graphql.Args() args: CreateAffectationArgs
  ): Promise<Affectation> {
    return await this.service.createAffectation({
      ...args,
      data: {
        ...args.data,

        domaine: {
          connect: args.data.domaine,
        },

        salarie: args.data.salarie
          ? {
              connect: args.data.salarie,
            }
          : undefined,

        structure: {
          connect: args.data.structure,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Affectation)
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "update",
    possession: "any",
  })
  async updateAffectation(
    @graphql.Args() args: UpdateAffectationArgs
  ): Promise<Affectation | null> {
    try {
      return await this.service.updateAffectation({
        ...args,
        data: {
          ...args.data,

          domaine: {
            connect: args.data.domaine,
          },

          salarie: args.data.salarie
            ? {
                connect: args.data.salarie,
              }
            : undefined,

          structure: {
            connect: args.data.structure,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Affectation)
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "delete",
    possession: "any",
  })
  async deleteAffectation(
    @graphql.Args() args: DeleteAffectationArgs
  ): Promise<Affectation | null> {
    try {
      return await this.service.deleteAffectation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Structure, {
    nullable: true,
    name: "domaine",
  })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "any",
  })
  async getDomaine(
    @graphql.Parent() parent: Affectation
  ): Promise<Structure | null> {
    const result = await this.service.getDomaine(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Salarie, {
    nullable: true,
    name: "salarie",
  })
  @nestAccessControl.UseRoles({
    resource: "Salarie",
    action: "read",
    possession: "any",
  })
  async getSalarie(
    @graphql.Parent() parent: Affectation
  ): Promise<Salarie | null> {
    const result = await this.service.getSalarie(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Structure, {
    nullable: true,
    name: "structure",
  })
  @nestAccessControl.UseRoles({
    resource: "Structure",
    action: "read",
    possession: "any",
  })
  async getStructure(
    @graphql.Parent() parent: Affectation
  ): Promise<Structure | null> {
    const result = await this.service.getStructure(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
