/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AffectationService } from "../affectation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AffectationCreateInput } from "./AffectationCreateInput";
import { Affectation } from "./Affectation";
import { AffectationFindManyArgs } from "./AffectationFindManyArgs";
import { AffectationWhereUniqueInput } from "./AffectationWhereUniqueInput";
import { AffectationUpdateInput } from "./AffectationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AffectationControllerBase {
  constructor(
    protected readonly service: AffectationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Affectation })
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAffectation(
    @common.Body() data: AffectationCreateInput
  ): Promise<Affectation> {
    return await this.service.createAffectation({
      data: {
        ...data,

        domaine: {
          connect: data.domaine,
        },

        salarie: data.salarie
          ? {
              connect: data.salarie,
            }
          : undefined,

        structure: {
          connect: data.structure,
        },
      },
      select: {
        activite: true,
        createdAt: true,

        domaine: {
          select: {
            id: true,
          },
        },

        id: true,

        salarie: {
          select: {
            id: true,
          },
        },

        structure: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Affectation] })
  @ApiNestedQuery(AffectationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async affectations(@common.Req() request: Request): Promise<Affectation[]> {
    const args = plainToClass(AffectationFindManyArgs, request.query);
    return this.service.affectations({
      ...args,
      select: {
        activite: true,
        createdAt: true,

        domaine: {
          select: {
            id: true,
          },
        },

        id: true,

        salarie: {
          select: {
            id: true,
          },
        },

        structure: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Affectation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async affectation(
    @common.Param() params: AffectationWhereUniqueInput
  ): Promise<Affectation | null> {
    const result = await this.service.affectation({
      where: params,
      select: {
        activite: true,
        createdAt: true,

        domaine: {
          select: {
            id: true,
          },
        },

        id: true,

        salarie: {
          select: {
            id: true,
          },
        },

        structure: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Affectation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAffectation(
    @common.Param() params: AffectationWhereUniqueInput,
    @common.Body() data: AffectationUpdateInput
  ): Promise<Affectation | null> {
    try {
      return await this.service.updateAffectation({
        where: params,
        data: {
          ...data,

          domaine: {
            connect: data.domaine,
          },

          salarie: data.salarie
            ? {
                connect: data.salarie,
              }
            : undefined,

          structure: {
            connect: data.structure,
          },
        },
        select: {
          activite: true,
          createdAt: true,

          domaine: {
            select: {
              id: true,
            },
          },

          id: true,

          salarie: {
            select: {
              id: true,
            },
          },

          structure: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Affectation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Affectation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAffectation(
    @common.Param() params: AffectationWhereUniqueInput
  ): Promise<Affectation | null> {
    try {
      return await this.service.deleteAffectation({
        where: params,
        select: {
          activite: true,
          createdAt: true,

          domaine: {
            select: {
              id: true,
            },
          },

          id: true,

          salarie: {
            select: {
              id: true,
            },
          },

          structure: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
